eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false


server:
  port: 8765 # HTTP (Tomcat) port